Import('env')
common = ['main.cc', 'tester.cc', 'reduce.cc', 'hist.cc']
env.Program('colour-naive', ['colour-naive.cc'] + common)
env.Program('colour-cv', ['colour-cv.cc'] + common)
env.Program('colour-cv-shift', ['colour-cv-shift.cc'] + common)
env.Program('colour-cv-compact', ['colour-cv-compact.cc'] + common)
env.Program('colour-ns', ['colour-ns.cc'] + common)
